### PR TITLE
Add tests and services to create attachments, templates, buttons

### PR DESCRIPTION
**Pull request by jrschumacher**

### CODE REVIEW

**Comment by jrschumacher** [comment]
I moved the examples into `examples` so we can run tests with `npm test`. There are a few tests left to do:

- test router
- test send
- test callback

**Comment by jrschumacher** [comment]
Also the readme needs to be updated to support the latest additions

**Comment by kelonye** [comment]
Meta :smile: ... also added you as a contributor.

**Comment by kelonye** [comment]
@jrschumacher added task as #3

**Pull request merged**
